In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
%matplotlib inline

In [2]:
df=pd.read_csv("C:\\Users\\dell\\Desktop\\Machine Learning\\Social.csv")

In [3]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [5]:
x=df.drop(['User ID','Purchased'],axis=1)
y=df['Purchased']

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
x['Gender']=LabelEncoder().fit_transform(x['Gender'])

In [8]:
x.columns

Index(['Gender', 'Age', 'EstimatedSalary'], dtype='object')

In [9]:
x.head()

Gender  Age  EstimatedSalary
0       1   19            19000
1       1   35            20000
2       0   26            43000
3       0   27            57000
4       1   19            76000

In [124]:
from sklearn.model_selection import train_test_split

In [125]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [84]:
from sklearn.neighbors import KNeighborsClassifier

In [85]:
model=KNeighborsClassifier(n_neighbors=5).fit(x_train,y_train)

In [86]:
pred=model.predict(x_test)

In [87]:
from sklearn.metrics import confusion_matrix,classification_report

In [88]:
print(confusion_matrix(y_test,pred))

[[46  6]
 [ 8 20]]


In [89]:
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       0.85      0.88      0.87        52
          1       0.77      0.71      0.74        28

avg / total       0.82      0.82      0.82        80



In [ ]:
model=GaussianNB().fit(x_train)

In [93]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
l=[]
for i in range(2,101):
    model=KNeighborsClassifier(n_neighbors=i).fit(x_train,y_train)
    pred=model.predict(x_test)
    l.append(mean_absolute_error(y_test,pred))

In [98]:
l

[0.2375,
 0.2,
 0.2,
 0.175,
 0.225,
 0.1875,
 0.225,
 0.2125,
 0.225,
 0.2,
 0.225,
 0.25,
 0.2375,
 0.225,
 0.25,
 0.225,
 0.2375,
 0.2375,
 0.25,
 0.225,
 0.2375,
 0.2375,
 0.2375,
 0.225,
 0.225,
 0.2125,
 0.2125,
 0.2125,
 0.225,
 0.2,
 0.2,
 0.2125,
 0.2,
 0.2,
 0.25,
 0.25,
 0.25,
 0.225,
 0.25,
 0.2375,
 0.25,
 0.2375,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.2625,
 0.275,
 0.2625,
 0.275,
 0.275,
 0.275,
 0.275,
 0.275,
 0.275,
 0.275,
 0.275,
 0.275,
 0.275,
 0.275,
 0.275,
 0.275,
 0.275,
 0.275,
 0.275,
 0.275]

In [96]:
max(l)

0.275

In [99]:
from sklearn.naive_bayes import GaussianNB

In [102]:
model=GaussianNB().fit(x_train,y_train)

In [103]:
pred=model.predict(x_test)

In [104]:
print(confusion_matrix(y_test,pred))

[[50  2]
 [ 3 25]]


In [105]:
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       0.94      0.96      0.95        52
          1       0.93      0.89      0.91        28

avg / total       0.94      0.94      0.94        80



In [126]:
from sklearn.svm import SVC

In [127]:
model=SVC(kernel="linear").fit(x_train,y_train)

In [128]:
pred=model.predict(x_test)

In [129]:
print(confusion_matrix(y_test,pred))

[[48  4]
 [ 8 20]]


In [130]:
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       0.86      0.92      0.89        52
          1       0.83      0.71      0.77        28

avg / total       0.85      0.85      0.85        80

